### ISSUE TITLE
Soap-UI ile çalışılabilir hale gelinmesi ve development ortamının hazırlanması

### ISSUE THREAD

**Issue by syigit** [COMU/soap-ws#1]

**Comment by ygokirmak** [comment]
@ozcanesen git ile uygulamayı çektikten sonra 

mvn eclipse:eclipse 

yazarak projeyi eclipse projesi haline getiriyorsun, 
bu işlem biraz uzun sürebilir, sonrasında eclipse import edebilirsin.

sonra şuradaki adımları izleyerek basit bir toplama cikarma servisi tanımlayabilirsin,
http://evam.com/blog/2013/12/using-web-service-to-call-an-evam-action/

son olarak da şu örneği kullanarak kendi yarattığın webservisi çağırabilirsin.

https://github.com/COMU/soap-ws/blob/master/soap-examples/quickstart/src/test/java/org/reficio/ws/quickstart/SoapClientExamplesTest.java

webservis yaratmak ve ayağa kaldırmak için bir application server kullanman gerekiyor,
tomcat kullanabilirsin.

bu aşamalar zahmetli aşamalar, 
sorularını geciktirmeden sor lütfen

**Comment by ozcan** [comment]
Selam,

tomcat üzerinde çalışan basit bir web servisi oluşturdum, wsdl dosyası [burada](https://gist.github.com/ozcanesen/8573192), soap-ws'i maven ile eclipse projesine çevirip import ettim.

basit bir request göndermek için soap-ws dökümanlarından şu örneği denedim.

```
    Wsdl wsdl = Wsdl.parse("http://localhost:8080/SimpleSOAPExample/services/Islem?wsdl");

    SoapBuilder builder = wsdl.binding()
        .localPart("IslemSoapBinding")
        .find();
    SoapOperation operation = builder.operation()
        .soapAction("topla")
        .find();

    String request = builder.buildInputMessage(operation);
```

dediğimde .find() kısmı `Found no operations` hatası veriyor. `IslemSoapBinding` yerine `Islem`, `topla` vs. yazmayı denedim işe yarmadı. 

Sonuç olarak geliştirme ortamı hazır ama soap-ws kütüphanesini nasıl kullanacağım hakkında pek bir fikrim yok.

**Comment by KancerEzeroglu** [comment]
Selam Özcan,

Öncelikle projeyi geliştirmende bir destekçin de ben olacağım. Elimden geldiğince sana yardım edeceğim. Bu proje bir şekilde ilerlediğinde gerçekten güzel şeyler ortaya çıkacak. Şimdi gelelim soruna bende soap-ws yi eclipse import ettim. Ama itiraf edeyim henüz bir deneme yapamadım. Ancak web servis ile ilgili geliştirdiğim bir kaç projede yaptığım kadarıyla sanırım kodun şurasında bir hata yapmışsın. Emin olmak için senin wsdl dosyasını kullanıp senin yaptığın gibi kütüphaneyi kullanmam lazım ama hızlı olmak adına önerimi yerelinde deneyebilirsen iyi olur.. Önerim şu;

Wsdl wsdl = Wsdl.parse("http://localhost:8080/SimpleSOAPExample/services/Islem?wsdl");

şeklinde yazmak yerine;

Wsdl wsdl = Wsdl.parse("http://localhost:8080/SimpleSOAPExample/services/Islem");

yazmayı deneyebilir misin?

**Comment by ozcan** [comment]
Selam Kancer,

Geçen hafta ve bu hafta hep mobil internet kullanıp pek fazla internete bağlanamadığımdan bu sorunla ilgili güncel durumumu belirtemedim. Sorunu yazdıktan sonraki gün Soap-UI aracıyla kendi lokalimdeki servisi inceledim senin dediğin şekilde wsdl ve endpoint adreslerini düzelttim, ek olarak operation'ı bulmak için action parametresini değil name parametresini kullandım (soap-ui de action kısmı boş görünüyordu). Sonuç olarak biraz deneme yanılma yoluyla da olsa elimde çalışan bir soap servisi oldu ve ona istek gönderip sonuç alabildim. Eğer geliştirme ortamının kurulması aşamasında başka yapmam gereken bir şey kalmadıysa yeni işler üzerinden ilerleyebiliriz.

**Comment by KancerEzeroglu** [comment]
Bu issue tamamlandı sanırım. @syigit issue kapatılabilir :)
