### ISSUE TITLE
Komut satırından ws çağıran uygulama

### ISSUE THREAD

**Issue by ygokirmak** [COMU/soap-ws#2]
Merhaba,

Basit bir uygulamayla başlayalım,
komut satırından ws çağıran bir uygulama olacak bu,
imzası şu şekilde olabilir, 

./callws -e "www.hede.com/services/Xservice/wsdl/Xservice.wsdl" --check-endpoint

endpointe ulaşıp ulaşamadığını, o endpointede düzgün bir wsdl olup olmadığını kontrol eder

./callws -e "www.hede.com/services/Xservice/wsdl/Xservice.wsdl" --list-operations

servis üzerinde olan operasyonları listeler

./callws -e "www.hede.com/services/Xservice/wsdl/Xservice.wsdl" -o sum --list-parameters

servisin "sum" adlı methodunun aldığı parametreleri listeler

./callws -e "www.hede.com/services/Xservice/wsdl/Xservice.wsdl" -o sum -p {param1:10,param2:20,param3:12 }

verilen değerlerle servisi çağırır ve sonucunu basar

ilk 3 basamak kütüphaneye biraz daha aşina olmanı sağlar fakat  son basamak çok kolay değil, soap-ws verdiğin bir parametreyle servisi çağırmanı sağlamıyor şu an, onun için kodun içine girip biraz değişiklik yapmak gerekecek.. Son basamağı biraz daha detaylandıracağım

@syigit tek issue olarak açtım ama uygunu bölmek midir?

**Comment by KancerEzeroglu** [comment]
@ozcanesen selam,

Bu yapılması gerekenleri tek bir issue da açtık ama bölünedebilir. Sen bunları yapmaya başla bence en kısa sürede. Herhangi bir noktada takılırsan bekleme hemen bana sor.

Kolay gelsin,
